apiVersion: apps/v1
kind: Deployment
metadata:
  name: astonvilla

spec:
  replicas: 1
  
  template:
    metadata:
      labels:
        app: astonvilla-pod
    spec:
      containers:
      - name: astonvilla
        image: nourchawebi/astonvilla-app:1.1.36
        ports:
        - containerPort : 80
        resources :
          requests:
            memory: "256Mi"
            cpu : "250m"
          limits: 
            memory: "512Mi"
            cpu: "500m"
  selector:
    matchLabels: 
      app : astonvilla-pod
